In [20]:
import requests
import json
import pandas as pd

response = requests.get('https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json')
data = response.json()

attributes = ['id', 'num', 'name', 'img', 'type', 'height', 'weight', 'candy', 'candy_count', 'egg', 'spawn_chance',
              'avg_spawns', 'spawn_time', 'multipliers', 'weaknesses', 'next_evolution', 'prev_evolution']

# Create an empty list to store the extracted data
pokemon_data = []

# Iterate over each Pokemon record and extract the desired attributes
#These nested loops iterate over each Pokémon record in the data dictionary and extract the desired attributes. 
#If the attribute exists in the Pokémon record, it is stored in the extracted_data dictionary. 
#If the attribute is a list, it is joined into a string using ", ". 
#For attributes 'multipliers', 'next_evolution', and 'prev_evolution', special handling is applied. 
#If the attribute does not exist in the Pokémon record, None is stored. 
#The extracted data for each Pokémon is then appended to the pokemon_data list.
for pokemon in data['pokemon']:
    extracted_data = {}
    for attribute in attributes:
        if attribute in pokemon:
            if isinstance(pokemon[attribute], list):
                if attribute == 'multipliers':
                    extracted_data[attribute] = ", ".join(str(entry) for entry in pokemon[attribute])
                elif attribute in ['next_evolution', 'prev_evolution']:
                    extracted_data[attribute] = ", ".join([f"{entry['num']} - {entry['name']}" for entry in pokemon[attribute]])
                else:
                    extracted_data[attribute] = ", ".join(pokemon[attribute])
            else:
                extracted_data[attribute] = pokemon[attribute]
        else:
            extracted_data[attribute] = None
    pokemon_data.append(extracted_data)

# Create a DataFrame from the extracted data
df = pd.DataFrame(pokemon_data)

# Save DataFrame to a CSV file
df.to_csv('pokemon_data.csv', index=False)

print("Data saved as 'pokemon_data.csv'")

Data saved as 'pokemon_data.csv'

In [18]:
data=pd.read_csv('/content/pokemon_data.csv')

In [19]:
data.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"Grass, Poison",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,1.58,"Fire, Ice, Flying, Psychic","002 - Ivysaur, 003 - Venusaur",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"Grass, Poison",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"1.2, 1.6","Fire, Ice, Flying, Psychic",003 - Venusaur,001 - Bulbasaur
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"Grass, Poison",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"Fire, Ice, Flying, Psychic",NaN,"001 - Bulbasaur, 002 - Ivysaur"
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,Fire,0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,1.65,"Water, Ground, Rock","005 - Charmeleon, 006 - Charizard",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,Fire,1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,1.79,"Water, Ground, Rock",006 - Charizard,004 - Charmander